grupa_projekt:
    resource: "@GrupaProjektBundle/Resources/config/routing.yml"
    prefix:   /

uek_demo:
    resource: "@UekDemoBundle/Resources/config/routing.yml"
    prefix:   /demo

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: @AppBundle/Controller/
    type:     annotation
