services:
#    uek_demo.example:
#        class: Uek\DemoBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
   pfuta_name_provider:
         class: Uek\Component\Name\NameProvider
         arguments: ["Jasio"]