grupa_projekt_homepage:
    path:     /
    defaults: { _controller: GrupaProjektBundle:Index:index }
grupa_projekt_index:
    path:     /index
    defaults: { _controller: GrupaProjektBundle:Index:index }