grupa_projekt_homepage:
<<<<<<< HEAD
    path:     /
    defaults: { _controller: GrupaProjektBundle:Index:index }
grupa_projekt_index:
    path:     /index
    defaults: { _controller: GrupaProjektBundle:Index:index }
=======
    path:    /
    defaults: { _controller:GrupaProjektBundle:Index:index }

grupa_projekt_index:
    path:    /index
    defaults: { _controller:GrupaProjektBundle:Index:index }

grupa_projekt_filmy:
    path:    /filmy
    defaults: { _controller:GrupaProjektBundle:Filmy:filmy }

grupa_projekt_movie_slug:
    path:    /filmy/{slug}
    defaults: { _controller:GrupaProjektBundle:Filmy:movie }

grupa_projekt_logowanie:
    path:    /login
    defaults: { _controller:GrupaProjektBundle:Index:logowanie }

grupa_projekt_zalogowany:
    path:    /zalogowany
    defaults: { _controller:GrupaProjektBundle:Index:zalogowany }

grupa_projekt_recenzja:
    path:    /zalogowany/recenzja
    defaults: { _controller:GrupaProjektBundle:Index:recenzja }
>>>>>>> d866de9b5c28131674f9ca706da61ed8b0b6ca31
